"""Synthetic tables and trap events; contains no captured guest table pages."""
import struct
from guest_pt import PAGE, MONITOR_TCR, MONITOR_MAIR
from replay_debug_probe import GuestMemory, CallbackReplay

HIGH = (1 << 64)-(1 << 47)
ENABLED_SCTLR = 0x02001010fc14793d
VHE_HCR = 0x408000000


class Tables:
    def __init__(self):
        self.base, self.size = 0x20000000, 0x4000000
        self.memory = GuestMemory(self.base, self.size)
        self.low, self.high = self.base+PAGE, self.base+2*PAGE
        self.next_table = self.base+0x100000
        self.memory.add_page(self.low)
        self.memory.add_page(self.high)
        self.pc = self.base+0x40000
        self.sp = HIGH+0x8000
        self.bootargs = self.base+0x90000
        self.pc_path = self.map(self.pc, self.pc)
        self.stack_path = self.map(self.sp-16, self.base+0x80000, flags=0x403 | (3 << 53))
        self.controls = dict(tcr=MONITOR_TCR, mair=MONITOR_MAIR, ttbr0=self.low, ttbr1=self.high)

    def get(self, location):
        address, index = location
        return struct.unpack_from('<Q', self.memory.pages[address], index*8)[0]

    def put(self, location, descriptor):
        address, index = location
        struct.pack_into('<Q', self.memory.pages[address], index*8, descriptor)

    def map(self, va, pa, flags=0x403):
        table = self.high if va >> 63 else self.low
        path = []
        for shift in (36, 25):
            location = (table, (va >> shift) & 0x7ff)
            path.append(location)
            descriptor = self.get(location)
            if not descriptor:
                child = self.next_table
                self.next_table += PAGE
                self.memory.add_page(child)
                self.put(location, child | 3)
            else:
                child = descriptor & ((1 << 42)-PAGE)
            table = child
        location = (table, (va >> 14) & 0x7ff)
        self.put(location, (pa & -PAGE) | flags)
        return path+[location]

    def endpoint(self, checkout, **kwargs):
        return CallbackReplay(checkout, memory=self.memory, entry=self.pc,
                              args_off=self.bootargs-self.base, **kwargs)

    def event(self, esr=0x5a006040, value=ENABLED_SCTLR, rt=0, *, mode=4):
        regs = [0x100+i for i in range(32)]
        regs[rt] = value
        return dict(reason=2, code=0, esr=esr, pc=self.pc, spsr=0xa00003c0 | mode,
                    regs=regs, sp=[self.sp, self.sp, 0], far=0)

    def access(self, endpoint, reg, read=False, value=0, rt=0):
        # Feed the HVC generated by the real probe instruction rewriter.
        op0, op1, crn, crm, op2 = reg
        word = (0xd5000000 | int(read) << 21 | op0 << 19 | op1 << 16 |
                crn << 12 | crm << 8 | op2 << 5 | rt)
        patched = endpoint.namespace['patch_probe_code'](struct.pack('<I', word))
        instruction, = struct.unpack('<I', patched)
        if instruction & 0xffe0001f != 0xd4000002:
            raise AssertionError('Synthetic instruction did not rewrite to HVC')
        return endpoint.feed(self.event(0x5a000000 | ((instruction >> 5) & 0xffff), value, rt))

    def configure(self, endpoint):
        s = endpoint.sysreg
        for register, value in [(s.HCR_EL2, VHE_HCR), (s.TCR_EL1, self.controls['tcr']),
                                (s.TTBR0_EL1, self.low), (s.TTBR1_EL1, self.high),
                                (s.MAIR_EL1, self.controls['mair'])]:
            self.access(endpoint, register, value=value)
            if endpoint.replies[-1] != int(endpoint.EXC_RET.HANDLED):
                raise AssertionError(endpoint.report)

    def enable(self, endpoint):
        self.configure(endpoint)
        return self.access(endpoint, endpoint.sysreg.SCTLR_EL2, value=ENABLED_SCTLR)
